name: dating_app
description: NeoNerds
publish_to: 'none'
version: 1.1.9+19

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  firebase_core: 2.21.0 # Firebase Core package required to use other firebase services
  firebase_auth: 4.12.1  # Used to Authenticate User Account (e.g. Sign in with Phone number, etc..)
  cloud_firestore: 4.12.2 # Used to Save User Data in Database
  firebase_messaging: 14.7.3 # Used to Send Push Notifications (e.g. New like, Visit and Message)
  firebase_storage: 11.4.1 # Used to Save User Profile Images on Cloud Storage
  cloud_functions: ^4.5.3
  google_mobile_ads: 3.1.0 # Used to Show Admob Ads in App (e.g. Banner Ads, Interstitial Ads (full screen), Native Ads and Rewarded Video Ads)
  # END 

  in_app_purchase: 3.1.11 # This plugin help us to Sell VIP Subscription Plans in app
  flutter_svg: ^2.0.9 # This plugin help us to use custom svg icons          
  flutter_launcher_icons: 0.13.1 # Used to generate app icon launcher for both platforms android and iOS 
  flutter_native_splash: 2.3.5 # Used to generate the app splash screen for both platforms android and iOS 
  country_code_picker: 2.0.2 # Used to Select User Country Code
  scoped_model: 2.0.0 # Used to Manage Application State
  image_picker: 1.0.4 # # Used to select images from the User's device image library or take a new photo using the camera
  image_cropper: 4.0.1 # Used to Crop/Rotate Selected images from user's device
  url_launcher: 6.2.1 # Used to open link schemes in application or browser
  geolocator: 9.0.2 # Used to get User location by GPS 
  geocoding: 2.1.1 # Used to translate User latitude and longitude coordinates into a readable address
  rxdart: 0.27.7 # required by geoflutterfire plugin that helps us to query users by geolocation center
  shimmer: 3.0.0 # Used to create placeholder widget while app is loading the image
  timeago: 3.6.0 # Used to create fuzzy timestamps: (e.g. "3 minutes ago")
  share: 2.0.4 # Used to share application content in other applications
  flutter_cupertino_datetime_picker: 3.0.0
  place_picker: 0.10.0 # This plugin help us to create Passport feature
  fluttertoast: 8.2.2 # For toast messages
  change_app_package_name: ^1.1.0
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.6.0

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/icons/
     - assets/lang/
 
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo4.png"

# Generate app logo for splash screen
flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/app_logo4.png"
  android: true
  ios: true   